### ISSUE TITLE
Hijacking GIT feature to ask about Vulkan

### ISSUE THREAD

**Issue by Chrjstoph** [httpdigest/lwjgl3-autostack#1]
Hi, sorry about this breach of topic but I read that you tried to implement omni directional shadows from Sascha Willems usiong subpasses.

Did you succeed?
I somehow need to tell the renderpass/subrenderpass which layer to write to. 

Best Regards

**Comment by httpdigest** [comment]
Hi,

you might be referring to: https://github.com/SaschaWillems/Vulkan/issues/50

In this case, the idea was that you don't need to render to a 2D texture six times and blit that to the cubemap layer you originally wanted to render to; but use six render subpasses each rendering to the respective cubemap face bound as 2D image attachment.
The only thing I wanted to "improve" on Sascha's demo was to avoid the image blitting.
I did not think layered rendering, or using a geometry at all, was worth it.

I haven't got around implementing it fully, but the theory proves it to be doable. :)

**Comment by Chrjstoph** [comment]
Hi, yes I am referring to that.

I also want to remove the copy.

And considered your Idea. However I failed to  select the cubeface/ layer for the several subpasses, as you have suggested.

A forum question yielded the following: 
https://forums.khronos.org/showthread.php/13205-Rendering-to-Layered-Texture-using-Subpasses?p=41029#post41029

How would you assign layers to attachments? 

In the end I implemented the layered rendering approach using GS. But it slows down considerably compared with the copy solution (GTX970). I will check on pascal, though.

**Comment by httpdigest** [comment]
> How would you assign layers to attachments?

Since a cubemap is just a 2D texture array, when creating the render target image, we use a VK_IMAGE_TYPE_2D with arrayLayers = 6.
See: https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkImageViewCreateInfo.html

Next, we create 6 image views on the individual array layers (cubemap faces) via viewType=VK_VIEW_TYPE_2D_ARRAY and baseArrayLayer=0..5 with layerCount = 1.

As a reference, also see how Direct3D 11 does it: http://richardssoftware.net/Home/Post/26
Also OpenGL is capable of using a cubemap face as a render target attachment with glFramebufferTexture2D. So I bet Vulkan can do it, too. :)

**Comment by Chrjstoph** [comment]
Thank you for your reply.

While I can understand the creation of six views to render on the faces, and maybe also the binding of attachments to a single framebuffer(?),
I struggle  to create a proper renderpass.

If you are interested, you can have a look: https://github.com/ChristophLGDV/Vulkan/tree/master/shadowmappingomniSubpass

I will continue tommorrow

Best Regards
Christoph

**Comment by Chrjstoph** [comment]
Update: 
The simultaneous rendering appears not something that can be done with a single renderpass as it must adress the same image (https://www.khronos.org/assets/uploads/developers/library/2016-vulkan-devday-uk/6-Vulkan-subpasses.pdf, page 50)

There are things like subpasses and secondary command buffer I have not the faintested about, yet.

Currently it appears to me that I have to duplicate the erntire offscreen pipeline 6 times.

Best Regards

**Comment by httpdigest** [comment]
Yes, you need subpasses, simply for the reason that only subpasses can specify framebuffer attachments.
The renderpass only specifies the _layout_/_kind_ of attachments, which the subpass attachments must be compatible to.

**Comment by Chrjstoph** [comment]
Do I also need a framebuffer per face/subpass/RT ? In that case I need to duplicate the pipeline (?).

**Comment by httpdigest** [comment]
No. The idea is to just swap/change the image views in the render _subpass_ when rendering inside _the same_ renderpass using _the same_ framebuffer. You need not use different framebuffers, because also framebuffers do not specify the exact image views as render targets, but only the available attachments (which are _not_ images), but attachment points where image views can be connected to, in order to render to the image the view points to.

**Comment by Chrjstoph** [comment]
OK,

that means I have 1 cubemapview for sampling 
and six other views for rendering, both pointing to the same image.

Said 6 views are the 6 attachements that I bind to a 1-layered framebuffer.
Now, the renderpass that gets bound to this framebuffer is created before the framebuffer.

During creation I define 6 subpasses with depthReference.attachment = face;

6 attachments and 6 subpasses. 

I am missing something as I fail to pass vkCreateRenderPass successfully

**Comment by Chrjstoph** [comment]
The subpass setup also includes the dependencies which I have no working knowledge about.

Ignoring them is possible, setting them up incorrectly crashes the program.

When rendering the command fails to submit due to attachment differences.
Currently the cubemap has only one face. THe otheres are not showing.

If you care, you can have a look at the source, if you are familiar with Willems stuff you should know your way around.
I'd be grateful

**Comment by Chrjstoph** [comment]
I give up, it appears that multiple layers bound via different attachments on one framebuffer does not work.

I can configure the number of layers and send as many subpasses but only the last pass/attachment gets executed.

I am not knowledgeable enough to solve this, (yet).
